Uebung2/config/routes.rb
Rails.application.routes.draw do
  get 'product_management/add'
  get 'product_management/show'
  get 'product_management/show_detail'
  get 'product_management/add'
  get 'product_management/modify'
  get 'product_management/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Uebung2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Uebung2/app/models/product.rb
class Product < ApplicationRecord
end

Uebung2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Uebung2/app/controllers/product_management_controller.rb
class ProductManagementController < ApplicationController

  def show
    @products = Product.find_each
  end

  def show_detail
    @id = params[:id]
    @product = Product.find(@id)
  end

  def add
    @param_name = params[:name]
    @param_price = params[:price]
    @last_product = Product.last
    @product_number = if !@last_product
                        1
                      else
                        Product.last.id + 1
                      end
    if @param_name.present? && @param_price.present?
      Product.create(name: @param_name, product_number: @product_number, price: @param_price)
      redirect_to action: 'show'
    end
  end

  def modify
    if params[:id].present?
      @updated = false
      @product = Product.find(params[:id])
      if params[:price].present?
        @updated = @product.update(price: params[:price])
      end
      if params[:name].present?
        @updated = @product.update(name: params[:name])
      end
      if @updated
        redirect_to action: 'show'
      end
    end
  end

  def delete
    if params[:id].present?
      Product.delete(params[:id])
      redirect_to action: 'show'
    end
  end
end

Uebung2/app/helpers/application_helper.rb
module ApplicationHelper
end

Uebung2/app/helpers/product_management_helper.rb
module ProductManagementHelper
end

Uebung2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uebung2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Produktverwaltung</h1>
    <%= yield %>
  </body>
</html>

Uebung2/app/views/product_management/add.html.erb
<h1>ProductManagement#add</h1>

<form action="/product_management/add" method="get">
  <label for="name">Name: </label><input type="text" name="name">
  <label for="price">Preis: </label><input type="text" name="price">
  <button type="submit"> Submit </button>
</form>
<a href="/product_management/show">Zurück zur übersicht</a>

Uebung2/app/views/product_management/delete.html.erb
<h1>ProductManagement#delete</h1>
<p>Find me in app/views/product_management/delete.html.erb</p>

Uebung2/app/views/product_management/modify.html.erb
<h1>ProductManagement#modify</h1>
<% if @product %>
  <form action="/product_management/modify/" method="get">
    <input type="text" name="id" hidden value="<%= @product.id %>">
    <input type="text" name="name" value="<%= @product.name %>">
    <input type="text" name="price" value="<%= @product.price %>">
    <button type="submit">Submit</button>
  </form>
<% end %>

Uebung2/app/views/product_management/show.html.erb
<h1>Show all Products</h1>
<table>
  <tr>
    <th>
      ID
    </th>
    <th>
      Name
    </th>
    <th>
      Product_Number
    </th>
    <th>
      Price
    </th>
    <th>
      Action
    </th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td>
        <%= product.id %>
      </td>
      <td>
        <%= product.name %>
      </td>
      <td>
        <%= product.product_number %>
      </td>
      <td>
        <%= product.price %>
      </td>
      <td>
        <a href="/product_management/show_detail/?id=<%= product.id %>">Details</a>
        <a href="/product_management/modify/?id=<%= product.id %>">Edit</a>
        <a href="/product_management/delete/?id=<%= product.id %>">Delete</a>
        <!-- <%= link_to "Details", product_management_show_detail_path({:id=>product.id}) %> -->
      </td>
    </tr>
  <% end %>
</table>
<a href="/product_management/add">Add new Product</a>

Uebung2/app/views/product_management/show_detail.html.erb
<% if @product %>
  <h1>Produkt - <%= @product.name %> details</h1>
  <table>
    <tr>
      <th>
        ID
      </th>
      <th>
        Name
      </th>
      <th>
        Product_Number
      </th>
      <th>
        Price
      </th>
      <th>
        Action
      </th>
    </tr>
    <tr>
      <td>
        <%= @product.id %>
      </td>
      <td>
        <%= @product.name %>
      </td>
      <td>
        <%= @product.product_number %>
      </td>
      <td>
        <%= @product.price %>
      </td>
      <td>
        <a href="/product_management/modify/?id=<%= @product.id %>">Edit</a>
      </td>
    </tr>
  </table>
  <%= %>
<% end %>
<a href="/product_management/show">Zurück zur übersicht</a>